### ISSUE TITLE
Xlib Window property setting

### ISSUE THREAD

**Issue by johnlane** [christopheraue/ruby-xlib-objects#1]
Hi, Thanks for this great library, It really was a godsend today!

**This is just some feedback for you** because what I wanted to do ended up being a little obscure. I wanted to set a property on a window in a Gtk application. I tried this:

    topw.property('_NET_WM_STRUT').set([0, 0, self.height, 0 ], :CARDINAL)

However that didn't work because `topw.property` returns `nil` if the property isn't set. I ended up doing the work of `XlibObj::WIndow::Property` myself:

    XlibObj::Window::Property.new(topw, '_NET_WM_STRUT').set(
                [0, 0, self.height, 0 ],
                :CARDINAL)

My full code snippet, for the benefit of others,

    topw = XlibObj::Window.new(XlibObj::Display.new(':0'), toplevel.window.xid)
    XlibObj::Window::Property.new(topw, '_NET_WM_STRUT').set(
                [0, 0, self.height, 0 ],
                :CARDINAL)
    XlibObj::Window::Property.new(topw, '_NET_WM_STRUT_PARTIAL').set(
                [0, 0, self.height, 0, 0, 0, 0, 0, x, x+width-1, 0, 0], 
                :CARDINAL)

That first line gives me a Xlib window object for a Gtk window object. I don't know if there's a cleaner way to achieve that!

**Comment by christopheraue** [comment]
There is [`Window#set_property(name, value)`](https://github.com/christopheraue/ruby-xlib-objects/blob/master/lib/window.rb#L61) which does `Property.new(win, name).set(value)` under the hood.

So this should work in your case: `topw.set_property('_NET_WM_STRUT', [0, 0, height, 0 ])`.

You also do not need to set the `:CARDINAL` type manually. It is [inferred from the property value](https://github.com/christopheraue/ruby-xlib-objects/blob/master/lib/window/property.rb#L156)

**Comment by johnlane** [comment]
Ah yes, `Window#set_property` is there indeed - I don't know how I missed that!

It would work if it were not for the fact that the type isn't inferred properly (it becomes `:INTEGER` and the property gets set incorrectly) and `Window#set_property`does not accept a `type` argument.

That actually threw me for a while when using `XlibObj::Window::Property.new` becuase I experienced the same issue and only discovered the incorrect type inference (`:INTEGER`) and the solution (explicitly passing `:CARDINAL`) after stepping through the code.

Here are properties after setting the longhand way:

     $ xprop _NET_WM_STRUT_PARTIAL _NET_WM_STRUT
    _NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 15, 0, 0, 0, 0, 0, 1600, 3519, 0, 0
    _NET_WM_STRUT(CARDINAL) = 0, 0, 15, 0

and the shorthand way

     $ xprop _NET_WM_STRUT_PARTIAL _NET_WM_STRUT
    _NET_WM_STRUT_PARTIAL(INTEGER) = 0, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0
    _NET_WM_STRUT(INTEGER) = 0, 0, 0, 0

Looking at the [code](https://github.com/christopheraue/ruby-xlib-objects/blob/master/lib/window/property.rb#L153), I suspect it's because I pass zero values in:
```ruby
if objects.any? { |o| o <= 0 }
     :INTEGER
```
Perhaps this is morphing into a bug report?

**Comment by christopheraue** [comment]
Yep, indeed. I pushed gem version 0.7.6 with the fix.
