### ISSUE TITLE
Pointer Functionality

### ISSUE THREAD

**Issue by johnlane** [christopheraue/ruby-xlib-objects#2]
I was trying to query and reposition the pointer but I could not find any implementation in the `xlib-objects` gem. Did I miss it?

What I want to do, I achieved using `xlib` but I'd prefer to use the cleaner object layer if support exists:
```ruby
class IntPtr < FFI::Struct
    layout  :value, :int
end
display = XlibObj::Display.new(':0')
root_window = Xlib.XRootWindow(display.to_native,0)
Xlib.XQueryPointer(display.to_native,
                   root_window,
                   IntPtr.new,
                   IntPtr.new,
                   mx = IntPtr.new,
                   my = IntPtr.new,
                   IntPtr.new,
                   IntPtr.new,
                   IntPtr.new)
Xlib.XWarpPointer(display.to_native,
                  Xlib::None,
                  root_window,
                  0, 0,
                  0, 0,
                  x, 10)
display.flush
```

Also, I want to submit a mouse click. I want to implement this Python code in Ruby:
```python
from Xlib.ext.xtest import fake_input
fake_input(display,X.ButtonPress,1, X.CurrentTime, X.NONE, x, 10)
```
which uses the [XTest extension](https://www.x.org/releases/X11R7.7/doc/libXtst/xtestlib.html). I don't think you have support for that but I thought I'd ask. I am working around the problem by using `xdotool` but I'd prefer to do it directly.
```ruby
%x(xdotool click 1)
```
I've spent a few hours today (well, all day really!), first trying to write native Xlib code and then looking for libraries and trying to fix up a FFI binding to `libxtst` and `libxdo`. However, it's messy and I've fallen back to the above one-liner for the time being.

**Comment by christopheraue** [comment]
An interface for pointers does not exist. XTest is also not implemented.
