### ISSUE TITLE
Not compatible with Ruby 2.0

### ISSUE THREAD

**Issue by liger1978** [christopheraue/ruby-xlib-objects#3]
The gem claims to be compatible with any version of Ruby but is actually only compatible with Ruby >=2.1, due to use of "required keyword arguments":

```
require "xlib-objects"
SyntaxError: /usr/local/share/gems/gems/xlib-objects-0.7.6/lib/event/selection_notify.rb:12: syntax error, unexpected ','
      def initialize(type:, target:, property:)
```

**Comment by christopheraue** [comment]
That's true. Backward compatibility wasn't taken into account when writing this gem.
